name: Build and Push Node

on:
  push:
    branches:
    - main

jobs:
  build-push-gamepower:
    if: ${{ github.repository == 'GamePowerNetwork/gamepower-node' }}
    runs-on: ubuntu-18.04
    steps:
    - name: Trigger playground inclusion
      uses: peter-evans/repository-dispatch@v1
      with:
        token: ${{ secrets.REPO_ACCESS_TOKEN }}
        repository: paritytech/substrate-playground
        event-type: gamepower-updated
        client-payload: '{"id": "gamepower"}'
