name: Publish Image

# Controls when the action will run.
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [master]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

env:
  IMAGE_NAME: gamepower-network
  IMAGE_ID: ghcr.io/gamepowernetwork/gamepower-network:${{ github.run_id }}

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  printTag:
    name: Print Tag
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    outputs:
      version: ${{ steps.get_version.outputs.VERSION }}

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Get the version
        id: get_version
        run: echo ::set-output name=VERSION::${GITHUB_REF/refs\/tags\//}

      - name: Print the version
        id: print_version
        run: echo ${{steps.get_version.outputs.version}}
