name: Publish Image

# Controls when the action will run.
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [main]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

env:
  IMAGE_NAME: gamepower-network
  REPO_NAME: gamepowernetwork

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  buildImage:
    name: Build Docker Image
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Build Container Image
        run: docker build . --file Dockerfile --tag $IMAGE_NAME

      - name: Log into GitHub Container Registry
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login https://ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Psh image to GitHub Container Registry
        run: |
          IMAGE_ID=ghcr.io/${{ env.REPO_NAME }}/$IMAGE_NAME:${{ github.run_id }}
          docker push $IMAGE_ID:latest
